# Generated by Django 4.2.7 on 2023-12-13 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register_questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerquestionvariant',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_variant_questions', to='register_questions.registerquestion'),
        ),
    ]
