# Generated by Django 4.2.7 on 2023-12-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ques_110', '0008_alter_question2variant_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestions',
            name='answer',
            field=models.BooleanField(default=False),
        ),
    ]
