# Generated by Django 4.2.7 on 2023-12-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_paymentaccounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_completed_110',
            field=models.BooleanField(default=False),
        ),
    ]
