# Generated by Django 4.2.7 on 2023-12-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_is_completed_110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maxfiylik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
    ]
